"""Add challenges tables

Revision ID: 20dc110a91e8
Revises: ff4f7ddd53dd
Create Date: 2025-03-11 07:40:22.814905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dc110a91e8'
down_revision = 'ff4f7ddd53dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('measurement_unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('measurement_unit')
        batch_op.drop_column('current_value')
        batch_op.drop_column('target_value')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
